[metadata]
name = assert-matcher
version = attr: assert_matcher.VERSION
author = Alexander Schepanovski
author_email = suor.web@gmail.com
url = http://github.com/Suor/assert-macther
description = Makes comparing nested data structures easy and glancable
long_description = file: README.rst
long_description_content_type = text/markdown
keywords = tests
license = BSD-2-Clause
license_files = LICENSE
classifiers =
    Development Status :: 4 - Beta
    Framework :: Pytest
    Intended Audience :: Developers
    License :: OSI Approved :: BSD License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy
    Topic :: Software Development :: Testing
    Topic :: Utilities

[options]
packages = find:
python_requires = >=3.9

[options.entry_points]
pytest11 =
    assert_matcher = assert_matcher.plugin

[bdist_wheel]
universal = 1

[tool:pytest]
minversion = 7.1.2
